"""Generate frontend/india_map.js: SVG paths of the 33 IMD meteorological subdivisions.

Source: data/processed/subdivision_boundaries.geojson (IMD subdivisions, WGS84, our codes).
Projection: equirectangular with longitude scaled by cos(22 deg), which keeps India's
proportions close to what readers expect. Geometry is simplified to keep the file small.

    ml/.venv/Scripts/python frontend/tools/make_india_map.py
"""
import json
import math
from pathlib import Path

from shapely.geometry import shape

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "data" / "processed" / "subdivision_boundaries.geojson"
OUT = ROOT / "frontend" / "india_map.js"
K = math.cos(math.radians(22.0))
W = 1000.0  # viewBox width; height follows the data's aspect ratio
TOL = 0.02  # degrees


def main():
    feats = json.loads(SRC.read_text(encoding="utf-8"))["features"]
    geoms = {f["properties"]["subdivision_code"]: shape(f["geometry"]).buffer(0) for f in feats}
    minx = min(g.bounds[0] for g in geoms.values())
    miny = min(g.bounds[1] for g in geoms.values())
    maxx = max(g.bounds[2] for g in geoms.values())
    maxy = max(g.bounds[3] for g in geoms.values())
    sx = W / ((maxx - minx) * K)
    H = (maxy - miny) * sx

    def xy(lon, lat):
        return round((lon - minx) * K * sx, 1), round((maxy - lat) * sx, 1)

    paths, labels, areas = {}, {}, {}
    for code, g in geoms.items():
        g = g.simplify(TOL, preserve_topology=True)
        polys = list(g.geoms) if g.geom_type == "MultiPolygon" else [g]
        d = []
        for p in polys:
            if p.area < 0.002:  # drop specks (tiny islands) that only add bytes
                continue
            for ring in [p.exterior] + list(p.interiors):
                pts = [xy(x, y) for x, y in ring.coords]
                d.append("M" + "L".join(f"{a},{b}" for a, b in pts) + "Z")
        paths[code] = "".join(d)
        c = g.representative_point()
        labels[code] = list(xy(c.x, c.y))
        areas[code] = round(g.area, 3)
    js = ("/* Generated by frontend/tools/make_india_map.py from IMD subdivision boundaries. */\n"
          f"var INDIA_MAP={json.dumps({'w': W, 'h': round(H, 1), 'paths': paths, 'labels': labels, 'areas': areas}, separators=(',', ':'))};\n")
    OUT.write_text(js, encoding="utf-8")
    print(f"wrote {OUT} ({len(js) / 1024:.0f} KB), viewBox 0 0 {W:.0f} {H:.0f}")


if __name__ == "__main__":
    main()
